FROM ubuntu:latest

MAINTAINER yogi

RUN apt-get update -y
RUN apt-get install -y python3-pip python3-dev
RUN apt-get install sqlite

COPY ./requirements.txt /app/requirements.txt

WORKDIR /app

COPY . /app

ENTRYPOINT [ "python3" ]
CMD [ "appy.py" ]
